server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://db-usuarios:3306/db_usuarios?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

custom:
  message: "Bienvenido al Microservicio de Usuarios y Equipos de Trabajo"